FROM ubuntu:18.04 as base

RUN mkdir /install
WORKDIR /install

RUN apt-get update && \
    apt-get install -y software-properties-common curl gnupg

RUN add-apt-repository ppa:kalon33/gamesgiroll -y

RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
        debhelper \
        dh-python \
        python3-all \
        python3-all-dev \
        python3-dev \
        python-dev \
        python-pip \
        python3-pip \
        python3-setuptools \
        python3-venv \
        build-essential \
        devscripts \
        dh-virtualenv \
        equivs \
        wget \
        apt-transport-https \
        ca-certificates

ENV PATH=/root/.local/bin:$PATH

COPY . /build/

# General requirements
RUN python3 -m pip install -U pip && pip3 install --ignore-installed --user \
    -r /build/requirements.txt \
    -r /build/requirements-grpc-runtime.txt

# Amazon S3
RUN pip3 install --ignore-installed --user -r /build/requirements-s3.txt

# Azure
RUN pip3 install --ignore-installed --user -r /build/requirements-azure.txt \
     && pip3 install --ignore-installed --user azure-cli

# Build medusa itself so we can add the executables in the final image
RUN pip3 install --ignore-installed --user /build
